name: Release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y
      - name: Get latest issue number
        id: get_issue
        run: |
          COMMIT_MESSAGE="${{ steps.get_commit.outputs.COMMIT_MESSAGE }}"
          if [[ "$COMMIT_MESSAGE" =~ ([Cc]lose[sd]?|[Ff]ix(e[sd])?|[Rr]esolve[sd]?)\s#([0-9]+) ]]; then
            ISSUE_NUMBER="${BASH_REMATCH[2]}"
            echo "::set-output name=ISSUE_NUMBER::$ISSUE_NUMBER"
          fi
      - name: Close issue
        uses: peter-evans/close-issue@v1
        if: success() && steps.extract_issue.outputs.ISSUE_NUMBER != ''
        with:
          issue-number: ${{ steps.extract_issue.outputs.ISSUE_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
